/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daftarbarang;

/**
 *
 * @author fiona
 */
public class frm_pemasok extends javax.swing.JFrame {

    /**
     * Creates new form frm_pemasok
     */
    public frm_pemasok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_namapemasok_pemasok = new javax.swing.JLabel();
        lbl_notelp_pemasok = new javax.swing.JLabel();
        lbl_namabarang = new javax.swing.JLabel();
        txt_namapemasok_pemasok = new javax.swing.JTextField();
        txt_kodepos_pemasok = new javax.swing.JTextField();
        lbl_hargamodal = new javax.swing.JLabel();
        txt_notelp_pemasok = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_lokasi_pemasok = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        lbl_action_pemasok = new javax.swing.JLabel();
        btn_tambah_pemasok = new javax.swing.JButton();
        btn_ubah_pemasok = new javax.swing.JButton();
        btn_hapus_pemasok = new javax.swing.JButton();
        btn_keluar_pemasok = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tambah Data"));

        lbl_namapemasok_pemasok.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        lbl_namapemasok_pemasok.setText("Nama Pemasok");

        lbl_notelp_pemasok.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        lbl_notelp_pemasok.setText("No Telp");

        lbl_namabarang.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        lbl_namabarang.setText("Kode Pos");

        txt_namapemasok_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namapemasok_pemasokActionPerformed(evt);
            }
        });

        lbl_hargamodal.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        lbl_hargamodal.setText("Lokasi");

        txt_notelp_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_notelp_pemasokActionPerformed(evt);
            }
        });

        txt_lokasi_pemasok.setColumns(20);
        txt_lokasi_pemasok.setRows(5);
        jScrollPane1.setViewportView(txt_lokasi_pemasok);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_namapemasok_pemasok)
                            .addComponent(lbl_notelp_pemasok))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_kodepos_pemasok, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txt_notelp_pemasok)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_namapemasok_pemasok)))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_hargamodal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_namabarang))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_namapemasok_pemasok)
                            .addComponent(txt_namapemasok_pemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_notelp_pemasok)
                            .addComponent(txt_notelp_pemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_kodepos_pemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_namabarang)))
                    .addComponent(lbl_hargamodal))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_action_pemasok.setFont(new java.awt.Font("Ubuntu", 2, 14)); // NOI18N
        lbl_action_pemasok.setText("ACTION");

        btn_tambah_pemasok.setText("SIMPAN");
        btn_tambah_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_pemasokActionPerformed(evt);
            }
        });

        btn_ubah_pemasok.setText("UBAH");
        btn_ubah_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubah_pemasokActionPerformed(evt);
            }
        });

        btn_hapus_pemasok.setText("HAPUS");
        btn_hapus_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_pemasokActionPerformed(evt);
            }
        });

        btn_keluar_pemasok.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btn_keluar_pemasok.setText("KEMBALI");
        btn_keluar_pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluar_pemasokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_action_pemasok)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_tambah_pemasok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_hapus_pemasok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_ubah_pemasok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_keluar_pemasok, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_action_pemasok))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_tambah_pemasok)
                            .addComponent(btn_ubah_pemasok))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_keluar_pemasok)
                    .addComponent(btn_hapus_pemasok))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Pemasok", "Nama Pemasok", "No Telp", "Kode Pemasok", "Lokasi"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        setSize(new java.awt.Dimension(1063, 593));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namapemasok_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namapemasok_pemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namapemasok_pemasokActionPerformed

    private void txt_notelp_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_notelp_pemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_notelp_pemasokActionPerformed

    private void btn_tambah_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_pemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tambah_pemasokActionPerformed

    private void btn_ubah_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubah_pemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ubah_pemasokActionPerformed

    private void btn_hapus_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_pemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hapus_pemasokActionPerformed

    private void btn_keluar_pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluar_pemasokActionPerformed
        hide();
    }//GEN-LAST:event_btn_keluar_pemasokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_pemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_pemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_pemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_pemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_pemasok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus_pemasok;
    private javax.swing.JButton btn_keluar_pemasok;
    private javax.swing.JButton btn_tambah_pemasok;
    private javax.swing.JButton btn_ubah_pemasok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_action_pemasok;
    private javax.swing.JLabel lbl_hargamodal;
    private javax.swing.JLabel lbl_namabarang;
    private javax.swing.JLabel lbl_namapemasok_pemasok;
    private javax.swing.JLabel lbl_notelp_pemasok;
    private javax.swing.JTextField txt_kodepos_pemasok;
    private javax.swing.JTextArea txt_lokasi_pemasok;
    private javax.swing.JTextField txt_namapemasok_pemasok;
    private javax.swing.JTextField txt_notelp_pemasok;
    // End of variables declaration//GEN-END:variables
}
